name: Deploy siren marker to server
on:
  push:
    branches:
      - main
jobs:
  deploy-siren-marker:
    name: Deploy siren marker
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Prepare node.js
        working-directory: ./script
        run: npm install
      
      - name: Generate siren markers
        working-directory: ./script
        run: node merge.js        
      
      - name: Upload files
        working-directory: ./script
        run: node upload.js        
        env:
            SFTP_HOST: ${{secrets.SFTP_HOST}}
            SFTP_USER: ${{secrets.SFTP_USER}}
            SFTP_PRIVATE_KEY: ${{secrets.SFTP_PRIVATE_KEY}}