name: Deploy icons to server
on:
  push:
    branches:
      - main
jobs:
  upload-siren-icons:
    name: Upload siren icons
    runs-on: ubuntu-latest
    steps:
      - name: Check out icons
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload icons per SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{vars.WSM_SRV_01_IP}}
          remote-user: ${{secrets.SIRENICONS_UPLOAD_USER}}
          remote-password: ${{secrets.SIRENICONS_UPLOAD_PASSWORD}}
          local-path: "icons"
          remote-path: "/sprite/siren-icons"
