name: Deploy siren marker to server
on:
  push:
    branches:
      - main
jobs:
  deploy-siren-marker:
    name: Deploy siren marker
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate siren markers
        working-directory: ./script
        run: |
            npm install
            node merge.js        
      - name: Upload siren markers
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{vars.SFTP_HOST}}
          remote-user: ${{secrets.SFTP_USER}}
          ssh-private-key: ${{secrets.SFTP_PRIVATE_KEY}}
          local-path: "./dist/siren-marker"
          remote-path: "/mapdata/sprite/siren-marker"
          sync: "full"
      - name: Upload siren icons
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{vars.SFTP_HOST}}
          remote-user: ${{secrets.SFTP_USER}}
          ssh-private-key: ${{secrets.SFTP_PRIVATE_KEY}}
          local-path: "./icons"
          remote-path: "/assets/siren-icons"
          sync: "full"
